wifi: mt76: mt7915: Fix buggy 802.11ax on non-mt7915 devices
openwrt/mt76 pull request #761
Opened 2023-03-12 13:58 UTC by cryobry

Fixes slow 802.11ax on Redmi AX6000, etc.

Partially reverts https://patchwork.kernel.org/project/linux-wireless/patch/20230301163739.52314-1-nbd@nbd.name/

Needs testing.

2023-03-23 18:59 UTC, cotequeiroz requested changes

2023-03-23 18:59 UTC, cotequeiroz commented on mt7915/init.c
> -		}
This does not look right.  I haven't tried to build it, but removing the bracket should fail, unless it was failing before the change.

2023-03-25 13:49 UTC, ThiloteE commented
https://forum.openwrt.org/t/802-11ax-worse-than-802-11ac-with-mt76-driver/126466/374

> This one seems to be the culprit. In the !dev->dbdc_support section.
> 
> IEEE80211_VHT_CAP_SUPP_CHAN_WIDTH_160MHZ |

2023-03-27 13:48 UTC, cryobry commented
> https://forum.openwrt.org/t/802-11ax-worse-than-802-11ac-with-mt76-driver/126466/374
> 
> > This one seems to be the culprit. In the !dev->dbdc_support section.
> > IEEE80211_VHT_CAP_SUPP_CHAN_WIDTH_160MHZ |

I updated the commit so that IEEE80211_VHT_CAP_SUPP_CHAN_WIDTH_160MHZ is only set on MT7916, could use testing.

2023-04-03 12:00 UTC, Anteus commented
As hnyman pointed out in my similar pull request for mt7915 (RT3200 router) you should amend the forum link in the comment and commit to:
https://forum.openwrt.org/t/802-11ax-worse-than-802-11ac-with-mt76-driver/126466

For reference my pull request https://github.com/openwrt/mt76/pull/768

2023-06-09 19:06 UTC, Headcrabed commented
So any news about this? I think we have to solve this problem before 23.05 landing, and it is at RC1 now.

2023-07-16 03:31 UTC, Headcrabed commented
@nbd168 could you also fix this? According to forum [posts](https://forum.openwrt.org/t/802-11ax-worse-than-802-11ac-with-mt76-driver/126466/611?u=stat_headcrabed), this problem still exists on mt7986 devices.
Besides, seems this speed issue is related with this? https://github.com/openwrt/mt76/issues/724

2025-06-12 05:47 UTC, closed without merging